### PR TITLE
Fixing lint

### PR DESCRIPTION
**Pull request by GmBodhi**
Fixing lint errors and warnings 
image

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Everything seems ok! I don't see anything wrong in the code or something else

**Review by Crispy-Cream — APPROVED** [review]
I went through the code on my phone and it looks like there are no big changes. Honestly I would just merge and test.

**Comment by Crispy-Cream** [comment]
Github actions is throwing some errors and I'm not sure the best way to handle them.

**Comment by GmBodhi** [comment]
I haven't completed this tho. I'll have to fix a few more errors and warnings... Might be a little late.

**Comment by GmBodhi** [comment]
Should we really discontinue cache?

**Comment by GmBodhi** [comment]
I think I've got an idea for better caching and updating the structure...

**Pull request merged**
